
version: '3.8'
services:
  db:
    image: postgres:15.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '14045:5432'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
  db:
    driver: local